Repository OxfordIHTM/ihtm-hackathon-2024, pull requests merged in 2024-02, with the labels that each got.

#15 create data dictionaries
  R/create_dictionary.R
  R/get_field_description.R
  data/child_dictionary.csv
  data/cmam_dictionary.csv
  data/maternal_dictionary.csv
  sudan_health_nutrition.R
Labels: documentation

#16 fix erroneous code on README
  README.Rmd
  README.md
Labels: bug, documentation

#21 update sudan maps
  R/get_sudan_maps.R
  README.Rmd
  README.md
  sudan_health_nutrition.R
Labels: data, refactor

#10 Determinants of maternal and child undernutrition
  sudan_health_nutrition_6.R
Labels: analysis, data

#24 first steps of bottle neck analysis for team Naruto; KPIs
  packages.R
  sudan_health_nutrition_1.R
Labels: analysis, data

#41 re-facto team scripts
  .github/workflows/check_overall_workflow.yaml
  packages.R
  sudan_health_nutrition_1.R
  sudan_health_nutrition_2.R
  sudan_health_nutrition_5.R
Labels: refactor, testing

#22 Neji- Calculated Indicators of Responsiveness
  CMAM programme responsiveness.R
  packages.R
  sudan_health_nutrition_5.R
Labels: analysis, data

#58 remove call to read data
  .github/workflows/check_overall_workflow.yaml
  sudan_health_nutrition_5.R
Labels: infrastructure

#59 refactor gha workflow
  .github/workflows/check_overall_workflow.yaml
Labels: bug, testing

#62 re-factor dev workflow
  README.Rmd
  README.md
  sudan_health_nutrition_2.R
  sudan_health_nutrition_5.R
  underweight children by state.png
Labels: refactor

#63 add Rmd template for full report
  .github/workflows/check_overall_workflow.yaml
  .gitignore
  reports/sudan_health_nutrition.Rmd
Labels: documentation

#64 add gha workflow for generating report website
  .github/workflows/check_overall_workflow.yaml
  .github/workflows/create_report_website.yaml
  sudan_health_nutrition_1.R
Labels: documentation, reporting, testing

#65 add dependency to rsync
  .github/workflows/create_report_website.yaml
Labels: bug, infrastructure, reporting

#66 tidy up reporting gha workflow
  .github/workflows/create_report_website.yaml
  .gitignore
Labels: documentation, reporting, testing

#67 add .gitkeep to not .gitignore
  .gitignore
Labels: cleaning

#68 sync rock lee with main
  sudan_health_nutrition.R
  sudan_health_nutrition_2.R
  sudan_health_nutrition_3.R
Labels: refactor
